# Generated by Django 2.1.3 on 2018-12-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20181220_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='todo_list',
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
