# Generated by Django 2.1.3 on 2018-12-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20181229_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='expDate',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
